export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_CARD = "GET_CARD";
export const GET_AUTHORIZATION = "GET_AUTHORIZATION"; 
export const SET_AUTHORIZATION = "SET_AUTHORIZATION"; 
export const RESET_IS_AUTH = "RESET_IS_AUTH"; 
export const GET_YEARS_SUCCESS = "GET_YEARS_SUCCESS";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
